# Generated by Django 3.0.3 on 2020-02-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_board_members_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_members',
            name='profile',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
