# Generated by Django 3.0.3 on 2020-02-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200222_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='', max_length=200)),
                ('content', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
