# Generated by Django 3.0.3 on 2020-02-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_pages_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
