# Generated by Django 3.0.3 on 2020-02-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_pages_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='path',
            new_name='page_path',
        ),
    ]
