# Generated by Django 3.0.3 on 2020-02-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0002_auto_20200221_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_members',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
