# Generated by Django 3.0.3 on 2020-02-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0005_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
