# Generated by Django 3.0.3 on 2020-02-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0009_auto_20200223_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='page_path',
            new_name='url_path',
        ),
    ]
