# Generated by Django 3.0.3 on 2020-03-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0013_auto_20200225_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='corp_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_member_name', models.CharField(default='', max_length=200)),
                ('app_websites', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
