# Generated by Django 3.0.3 on 2020-03-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0014_corp_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corp_members',
            old_name='app_websites',
            new_name='website',
        ),
    ]
