# Generated by Django 3.0.3 on 2020-03-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0015_auto_20200306_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='corp_members',
            name='type_name',
            field=models.CharField(default='corporate-members', max_length=200),
        ),
    ]
