# Generated by Django 3.0.3 on 2020-03-08 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0016_corp_members_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corp_members',
            name='type_name',
        ),
        migrations.AddField(
            model_name='corp_members',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corp_members',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
