# Generated by Django 3.0.3 on 2020-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0018_auto_20200308_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('resource_name', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
