# Generated by Django 3.0.3 on 2020-03-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0019_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('sponsor_name', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
