# Generated by Django 3.0.3 on 2020-03-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0020_sponsors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sponsors',
            new_name='sponsors_list',
        ),
    ]
