# Generated by Django 3.0.3 on 2020-03-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0021_auto_20200310_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sponsors_list',
            new_name='sponsors',
        ),
    ]
