# Generated by Django 3.0.3 on 2020-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0022_auto_20200310_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_members',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
