# Generated by Django 3.0.3 on 2020-03-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0023_board_members_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_members',
            name='image_url',
        ),
    ]
