# Generated by Django 3.0.3 on 2020-03-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0024_remove_board_members_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='sponsor_logo',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='board_members',
            name='profile_pic',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=''),
        ),
    ]
