# Generated by Django 3.0.3 on 2020-03-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0025_auto_20200315_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_members',
            name='profile_pic',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='board'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='website',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='sponsor_logo',
            field=models.ImageField(blank=True, default='no-image-sponsor.png', null=True, upload_to='sponsors'),
        ),
    ]
