# Generated by Django 3.0.3 on 2020-03-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0026_auto_20200318_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='website',
            field=models.CharField(blank=True, default='--', max_length=200),
        ),
    ]
