# Generated by Django 3.0.3 on 2020-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0027_auto_20200318_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=2000)),
                ('meta_keywords', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='board_members',
            name='profile_pic',
            field=models.ImageField(blank=True, default='img/board/no-image-board.png', null=True, upload_to='img/board'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='sponsor_logo',
            field=models.ImageField(blank=True, default='img/sponsors-links/no-image-sponsors-links.png', null=True, upload_to='img/sponsors-links'),
        ),
    ]
