# Generated by Django 3.0.3 on 2020-03-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0029_auto_20200328_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='meta_keywords',
            field=models.CharField(default='', max_length=200),
        ),
    ]
