# Generated by Django 3.0.3 on 2020-03-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_websites', '0030_auto_20200328_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='meta_description',
            field=models.CharField(default='British Canadian Business Association', max_length=2000),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_keywords',
            field=models.CharField(default='British Canadian Business Association, BCBA', max_length=200),
        ),
        migrations.AlterField(
            model_name='meta',
            name='meta_title',
            field=models.CharField(default='British Canadian Business Association', max_length=200),
        ),
    ]
