# Generated by Django 3.0.3 on 2020-03-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
