# Generated by Django 3.0.3 on 2020-03-08 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0002_auto_20200307_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
