# Generated by Django 3.0.3 on 2020-03-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0003_auto_20200308_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_edited',
        ),
    ]
